name: eco_barrio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+20

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  permission_handler: ^11.3.0

  flutter:
    sdk: flutter
  #C
  cloud_firestore: ^4.17.5
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.6
  #F
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.2.1
  fl_chart: ^0.68.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  flutter_map: ^5.0.0
  flutter_image: ^4.1.11
  flutter_svg: ^1.0.0
  firebase_database: ^10.0.7
  #G
  google_maps_flutter: ^2.9.0
  geolocator: ^11.1.0
  google_sign_in: ^6.2.1
  geocoding: ^2.0.0
  table_calendar: ^3.0.8

  #H
  http: ^1.1.0
  #I
  image_picker: ^1.1.1
  intl: ^0.19.0
  #L
  location: ^5.0.3
  latlong2: ^0.9.1
  #M
  mobile_scanner: ^5.1.1
  qrscan: ^0.3.3
  #P
  package_info_plus: ^4.2.0
  provider: ^6.1.2
  #S
  shared_preferences: ^2.2.3
  share_plus: ^7.0.2
  #U
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
